### ISSUE TITLE
Searching for more than 5 tags is broken if the tag includes unicode.

### ISSUE THREAD

**Issue by Wulfre** [Wulfre/e621dl#1]
My tag aliasing method is put together in a hacky manor and is breaking some functionality. A specific case I have discovered is with the tag 'pokemon' which contains the unicode character 'é' in the e621 tag list and breaks the script.

I will clarify this issue in the future when I have more information.

**Comment by Wulfre** [comment]
When using the following tag group, searching for the full 6 tags works as expected.

```
[Test]
tags = score:>=1, rating:s, chubby, tuft, male, mammal
```

Tag aliasing will need to be developed further to fix this problem with specific tags as mentioned above.

**Comment by ssz333** [comment]
I had no issues with multitags until last sunday, downloader doesn't work since then - even if i reduce amount of tags, i'm still having same error - http://i.imgur.com/I2Tj5Y2.png
