### ISSUE TITLE
ERROR    The tag *_obese is spelled incorrectly or does not exist.

### ISSUE THREAD

**Issue by Youboontoo** [Wulfre/e621dl#10]
While executing the e621dl.exe file on my computer, I came across the following error:
`remote      ERROR    The tag *_obese is spelled incorrectly or does not exist.`

I'm using Windows 10 Version 10.0.17025.1000 and Python 3.6.3. I believe your script doesn't have any way of handling wildcard characters, and when it encounters any, it crashes.

**Comment by Youboontoo** [comment]
I suppose I should have said that this tag (along with "fluffbugveyll") was listed under `[blacklist]` in the config.ini file.

**Comment by Wulfre** [comment]
That's correct. I actually specified in the documentation that meta tags break the script, but I never actually went back to implement them. I'm trying to make a minimal number of calls to the API, so I'll just have to manually interpret wildcards, but that should be an easy fix. Look out for an update late tonight.

**Comment by Wulfre** [comment]
Okay, new release is up. Let me know if it works how you expected.

**Comment by Youboontoo** [comment]
```
youboontoo@tux-server:~/Documents/New folder$ python e621dl.py
File "e621dl.py", line 74
SyntaxError: Non-ASCII character '\xe2' in file e621dl.py on line 74, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Plus, there was no .exe for me to run, so I tried this out on my Ubuntu 17.04 build. 

Here's the `uname -a` info:
`Linux tux-server 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:33:07 UTC 2017 i686 i686 i686 GNU/Linux`
Here's the `python --version` info:
`Python 2.7.1`

**Comment by Youboontoo** [comment]
Apologies, didn't see the .exe until now. Thanks for everything!

**Comment by Wulfre** [comment]
Great, so it works now? Also, if you want to run from source you need to use python 3.
