### ISSUE TITLE
Please, don't remove the MD5 checksum in the file name!

### ISSUE THREAD

**Issue by xiveslestian** [Wulfre/e621dl#11]
I download a LOT of stuff and the MD5 name is the only way to check for errors.
Sometimes the downloads crash and the file is corrupted/not fully downloaded.

When you have 200GB+ of downloaded files using renamer tool to compare [PostName]_[MD5].[ext] to existing files is the only possible way to find corrupted files.
I am using [http://www.den4b.com/products/renamer](url) for that.

At least put the option for filenames - with just postname, and postname_md5

Thank you!

**Comment by Wulfre** [comment]
I'll see what I can do to put the option in, if you still need it after the latest update. I changed it because the program scans for incomplete downloads now, so the md5 wasn't useful to me anymore and it was easiest to resume the download if the filename had less information in it.

**Comment by Wulfre** [comment]
Okay, it will be back in the next release. Just add the following to your config:

```
[Other]
include_md5 = true
```

The only difference is the separating character is no longer `-` and is now `.`.
