### ISSUE TITLE
Add "min_FavoritesCount" in Search Group Keys

### ISSUE THREAD

**Issue by freelze** [Wulfre/e621dl#14]
Most pictures are low-scored but relatively high favorites ,
because most people will add pictures to their favorite instead of upvote it.
I think adding min_favCount in keys can make the search results more precise.

**Comment by Wulfre** [comment]
That's a really good point. I'm guilty of that myself and I didn't even think about it. I'll look into that tonight.

**Comment by Wulfre** [comment]
Added to main branch. Let me know if it works well for you.

**Comment by freelze** [comment]
I had already used it and It works well , thanks.
