### ISSUE TITLE
Download from the beginning?

### ISSUE THREAD

**Issue by ShadowRylander** [Wulfre/e621dl#15]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; Would it be possible to specify a `days` value which downloads files from the first upload of the artist to the present? I realize I might be able to use the `date:` tags, but I am unsure as to whether or not the `days` value will conflict with the tag. Would it be possible to implement such a system?
&nbsp;&nbsp;&nbsp;&nbsp; Thank you kindly for your consideration on the matter!

**Comment by Wulfre** [comment]
In this case I would just set the days value to something massive like 2000000000 and do a search with the artist as a tag.

**Comment by ShadowRylander** [comment]
Is there an upper limit to the days value?

**Comment by Wulfre** [comment]
There is a soft limit of 2147483647, but Python does a really good job of handling and correcting numbers that are above that limit.

**Comment by ShadowRylander** [comment]
Ah; thank you very much, then!
