### ISSUE TITLE
Non-ASCII character

### ISSUE THREAD

**Issue by fuchmii** [Wulfre/e621dl#17]
When I attempt to run e621dl on Pop!_OS 17.10 with the latest release of Python and Requests it produces the following syntax error:
```
SyntaxError: Non-ASCII character '\xe2' in file e621dl.py on line 129, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
I saw that adding ```# coding: utf-8``` to the top of the file would fix the syntax error. So far, that seems to work.

**Comment by Wulfre** [comment]
Thank you for the information. I will include this in one of the next commits.
