### ISSUE TITLE
Problem with .swf and .webm files

### ISSUE THREAD

**Issue by xiveslestian** [Wulfre/e621dl#2]
When i restart the download - i see message - something about checking for bad files, and the downloader deletes ALL .swf and .webm files from download folder.

my settings file looks like this:
[Settings]
last_run = 2017-01-01
parallel_downloads = 2

[Blacklist]
tags =

[explicit_50_jpg]
tags = rating:explicit, score:>=50

Also, i sometimes get bad downloads, and there is no way to check the md5 now, since the files are named by the number of the post. Is there a way to make filenames md5.ext (like the original e621dl) or post_number_md5.ext.
That i way i cold just use a program to compare filenames to their checksums and delete all bad downloads.

**Comment by Wulfre** [comment]
I apologize for your files being deleted. I had figured that there would be a problem with non-image filetypes but I completely forgot to test that before pushing a release.

I was thinking of useing the md5 sums to check for bad files, but I never got around to it. Currently, the script only checks if the file is an __image__, so it does not work in every case. I can definitely add back in the md5 data for each post. 

I've been working on simplifying the process for some of the friends that I've had testing so it's become really dumbed down and there are no settings left to configure. I will probably bring back some of the settings now that a lot of the functionality I was trying to add is implemented.

**Comment by Wulfre** [comment]
I just published an update which should fix this issue. Damaged files will be compared to their md5 hashes instead of their filetypes.

**Comment by xiveslestian** [comment]
That was fast!
Will do a test run for the night
