### ISSUE TITLE
Why duplicate copying was removed? Is it ideological, or is it technical?

### ISSUE THREAD

**Issue by lurkbbs** [Wulfre/e621dl#20]
Like, It should be an option or it should be hard-linking or it makes the script too complex so it should not be at all?

**Comment by Wulfre** [comment]
Apologies for slacking on the project and being transparent with communication. I got really busy this semester at school. 

It was an ideological reason, I like to keep the code as simple as possible, and re-downloading a few images is not usually a large tax on internet or storage. In addition, just creating links can break expectations if the original file is deleted but the link is still in place. Ideally, there would be a way to prevent duplicates at all, but that could end up breaking apart the searches that users define.

**Comment by lurkbbs** [comment]
OK. I understand.
BTW, hardlinks are essentially one file with 2+ different names, so you can't delete a file unless all links are deleted.
