### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by FatalFuZion** [Wulfre/e621dl#21]
I’ve been having issues with installing it. Could you make a really detailed step by step installation guide? I’ve done everything it says (I’m using the exe by the way) but it just opens and says there’s an error or it closes automatically. Please help

**Comment by lurkbbs** [comment]
OK,

1. Start program first, preferably if executable is the only file in a folder

**Comment by FatalFuZion** [comment]
okay, it opened and closed and made config.ini in the folder

**Comment by FatalFuZion** [comment]
okay, what should I change about the config.ini file? like if I wanted to add the tag 'male' what would I do?

**Comment by lurkbbs** [comment]
I think I just answered ;-)

**Comment by FatalFuZion** [comment]
my bad, I didn't see it

**Comment by lurkbbs** [comment]
No no, "what would I do?" question was asked seconds before I complete edit

**Comment by lurkbbs** [comment]
You're welcome! By the way, you can make more then one folder in the config.ini, like

```
 [Cute Cats]
 days = 30
 ratings = s
 min_score = 5
 tags = cat, cute

 [Cute Dogs]
 days = 30
 ratings = s
 min_score = 5
 tags = dog, cute
```

And I strongly recommend use the latest version should there be some problems with connection.
Just 
1. Install Python 3. Make sure to to check something like "Assosicate with .py"
2. Download latest source from https://github.com/Wulfre/e621dl (Green button "clone or download" --> "download to desktop")
3. Unpack zip in some folder
4. Double click e621dl.py instead of e621dl.exe

**Comment by FatalFuZion** [comment]
when I double click on e621dl.py it opens and closes

**Comment by lurkbbs** [comment]
Hm.
In folder in Explorer, shift+right click on emtpy space and select "Command line" or "powershell".
Type `python e621dl.py`
Copy results here

**Comment by FatalFuZion** [comment]
python e621dl.py
'python' is not recognized as an internal or external command,
operable program or batch file.

I downloaded the latest version of python from python.org

**Comment by lurkbbs** [comment]
It's all right, python is just not in "PATH" variable.
Try open python console from Start Menu

print there
`import sys; sys.executable`
then press Enter (Sorry if it's obvious, I just have to make sure)
the should be something like that:
`'C:\\Python37\\python.exe'`

with path known, replace `python e621dl.py` with 
`C:\\Python37\\python.exe e621dl.py`

**Comment by FatalFuZion** [comment]
when I put 'import sys; sys.executable' I get 
'C:\\Users\\-\\AppData\\Local\\Programs\\Python\\Python37-32\\python.exe' 

sorry for not knowing what this means, but where do I replace it? When I've tried
'C:\\Users\\-\\AppData\\Local\\Programs\\Python\\Python37-32\\python.exe e621dl.py' 
it says 
File "<stdin>", line 1
    C:\\Users\\-\\AppData\\Local\\Programs\\Python\\Python37-32\\python.exe e621dl.py
                                                                                        ^
SyntaxError: unexpected character after line continuation character

**Comment by lurkbbs** [comment]
Relax, everything is fine. 
In folder with e621dl.py in Explorer, shift+right click on emtpy space and select "Command line" or "powershell".
Type
`"C:\Users\-\AppData\Local\Programs\Python\Python37-32\python.exe" e621dl.py`
Copy results here.

P.S. "C:\Users\-\AppData\Local\Programs\Python\Python37-32\" is just a folder with python executable

**Comment by FatalFuZion** [comment]
Traceback (most recent call last):
  File "e621dl.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by lurkbbs** [comment]
Oops, forgot about this module
enter
`"C:\Users\-\AppData\Local\Programs\Python\Python37-32\python.exe" -m pip install requests`
in the command line. It should install needed dependencies

**Comment by lurkbbs** [comment]
Oh, and then again
"C:\Users\-\AppData\Local\Programs\Python\Python37-32\python.exe" e621dl.py

**Comment by FatalFuZion** [comment]
It's working now, thanks a lot :)

**Comment by lurkbbs** [comment]
Double click should works as well now. And you can always use latest version, of course.
Again, you're welcome :-)

**Comment by Wulfre** [comment]
Thanks @lurkbbs for being so helpful while I was inactive.

**Comment by lurkbbs** [comment]
You're welcome!
