### ISSUE TITLE
Program closing before searching.

### ISSUE THREAD

**Issue by darkspyro92** [Wulfre/e621dl#24]
For some reason the program closes before it even begins to search. Not sure why that is. I could maybe try running the python version and see if it gives me an error code.

**Comment by Wulfre** [comment]
Sorry for not replying for almost a month. I've been working on school projects so I haven't looked back at this repo in a while. The latest release works for me right now, so I'm not sure if it was just a temporary error.

The latest python version is fairly different from the last Windows release I built, so if you ever did get to trying that, let me know if anything was different.

**Comment by darkspyro92** [comment]
This is what it gives me.

![image](https://user-images.githubusercontent.com/22324730/45783612-4662c700-bc34-11e8-86e6-86bebe7ffe51.png)

**Comment by darkspyro92** [comment]
So the problem with the Windows version is the naming of Pokemon. Usually the parser renames that for me, so I'm not sure why it would be throwing a fit now.

![image](https://user-images.githubusercontent.com/22324730/45926869-768dbc80-bef7-11e8-894d-3c6579a00536.png)

**Comment by lurkbbs** [comment]
API handling problem, actually. Possible aliases are on many pages, but e621dl process only first page. I think API just changed suddenly. I'll make some pull request tomorrow.

**Comment by lurkbbs** [comment]
Fixed:
https://github.com/Wulfre/e621dl/pull/30
https://github.com/lurkbbs/e621dl/tree/patch-1
