### ISSUE TITLE
e621.dl.exe - Point of entry not found...

### ISSUE THREAD

**Issue by Max-RedHoodWolf-White** [Wulfre/e621dl#25]
Hello Wulfre! I'm so sorry for wasting your precious time with this stupid person...
I known you have more important things to do but...
All time i execute the e621.dl, show this
"The entry point of the ucrtbase.terminate procedure could not be located in the api-ms-win dynamic-link library crt-runtime-l1-1-0.dll."
I translated from Portuguese (Brazil)
Any suggestions what i can do?

I'm so happy and grateful for talking with you, thanks and sorry one more time!
See ya!

**Comment by Wulfre** [comment]
Sorry for being late to reply. It looks like that error is a problem with the installation of the C Runtime. Make sure you have the latest updates for Windows. 

Also, here is a download the version of the latest C Runtime included with Windows 10. I created the exe file on Windows 7 to try and improve compatibility, but this might help as a last resort.
https://www.microsoft.com/en-us/download/details.aspx?id=48234

**Comment by Wulfre** [comment]
That C Runtime is for installation on Windows 7. It installs the Windows 10 C Runtime on older editions of Windows for compatibility.
