### ISSUE TITLE
Program does not download anything

### ISSUE THREAD

**Issue by justwantittowork** [Wulfre/e621dl#34]
I'm using the exe version of the program and input some tags. The program created the folder it was all supposed to go into and showed the interface as if it had downloaded things, but all values were set to 0. The program then said it was done and to hit enter to exit. As expected, nothing had been downloaded. I have no idea what is causing this, and would like help with it; as well as bringing this to the attention of the devs. Thank you in advance.

**Comment by justwantittowork** [comment]
![It does this](https://user-images.githubusercontent.com/53221922/61720815-7b98e380-ad35-11e9-89a6-a1d3e2176863.PNG)
I just thought to add an image incase my description didn't illustrate the problem well enough.

**Comment by lurkbbs** [comment]
Are you absolutely sure your tags have any results if, e.g. if you search them directly on e621? Or that days, rating, min_score and favs are permissive enough? Also, try to remove tags one by one.
Also, if everything fails, you can try my fork here:
https://github.com/lurkbbs/e621dl/releases

**Comment by justwantittowork** [comment]
I know they're on e621, even if they're a little spicy. I'll try yours though. Thanks!

**Comment by lurkbbs** [comment]
You're welcome!
