### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by Cupears** [Wulfre/e621dl#40]
Is there a way to login at the moment to see hidden posts?
Been tinkering with it and not that great with code.

**Comment by Wulfre** [comment]
You need to add your username and api key to config.yaml see constants.py for the config template and fill in the login section. It's not fully implemented yet so I didn't have any written information on it.

**Comment by Cupears** [comment]
Ah alright

**Comment by RedFoxNightfox** [comment]
doesn't seem to work. allowed the generation of a new default config.yaml, input my username and api key, and ran the e621dl.py, and it told me that no login was detected.

**Comment by RedFoxNightfox** [comment]
Has anyone had success with getting the new username/api key setup to work?

**Comment by Cupears** [comment]
With messing around with things i learned that if you space your username from "username:" it doesn't read it but if you remove the space it comes out with an error saying...
('username': config['login'].get('username'),
AttributeError: 'str' object has no attribute 'get')

I dunno I'm just gonna mess with stuff.

**Comment by Cupears** [comment]
So what i did is that just leave a space between the "username:" and the "api_key:" from the colons. When you download whatever your downloading it will say no no login detected but it is downloading non-guest works.

**Comment by Cupears** [comment]
also one thing ill like to add is that when you start another search that you haven't finished it will come up with an error until you delete the unfinished files.
~last call~
File ".\e621dl.py", line 80, in <module>
    remote.finish_partial_downloads(session)
  File "P:\**********\e6\e621dl\remote.py", line 159, in finish_partial_downloads
    url = get_posts(f"id:{post_id}", 0, post_id + 1, session)['posts'][0]['file']['url']
TypeError: get_posts() missing 1 required positional argument: 'session'

**Comment by Wulfre** [comment]
I'll look into that. I pushed the login implementation too early I guess, but I'm glad people are at least finding the issues.

**Comment by Wulfre** [comment]
I figured out what I did wrong. Next update should work properly.
