### ISSUE TITLE
'NoneType' object not itterable Error when blacklist empty

### ISSUE THREAD

**Issue by MLausch1** [Wulfre/e621dl#42]
If the Blacklist section is empty the following error is thrown, 

Traceback (most recent call last):
  File ".\e621dl.py", line 115, in <module>
    elif [x for y in tags if any(fnmatch(x, y) for y in blacklist)]:
  File ".\e621dl.py", line 115, in <listcomp>
    elif [x for y in tags if any(fnmatch(x, y) for y in blacklist)]:
TypeError: 'NoneType' object is not iterable

Config File is attached 

[config - Copy.txt](https://github.com/Wulfre/e621dl/files/4427387/config.-.Copy.txt)

**Comment by Wulfre** [comment]
I forgot to put a default value for empty blacklists. Next update should fix this. Thanks for the info!
