### ISSUE TITLE
Abruptly (as of 5/26/21) getting 403 errors immediately on launch

### ISSUE THREAD

**Issue by kingretard** [Wulfre/e621dl#47]
I've been happily using this program for a few years now to keep my library up to date, but recently it has ceased to function without any change to my config.yaml. 
Specifically, I'm getting the following:

`[i] Running e621dl version 5.0.0.`
`[i] Getting config...`
`[i] Getting posts for search 'ardan_norgate'.`
`Traceback (most recent call last):`
`  File ".\e621dl.py", line 42, in <module>`
`    posts = remote.get_posts(client, ' '.join(search['tags']), search['start_date'], last_id)`
`  File "D:\Downloaders\E621DL\e621dl\remote.py", line 12, in get_posts`
`    response.raise_for_status()`
`  File "C:\Users\Mark\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpx\_models.py", line 841, in raise_for_status`
`    raise HTTPError(message, response=self)`
`httpx._exceptions.HTTPError: 403 Client Error: Forbidden for url: https://e621.net/posts.json?limit=320&tags=ardan_norgate+date%3A%3E%3D1994-01-10+`
`For more information check: https://httpstatuses.com/403`

I'm not entirely sure what's causing this 403. I'm not [currently] behind a VPN, I don't believe my account is banned (I'm able to browse normally), etc. I'm able to manually access the URL in question (https://e621.net/posts.json?limit=320&tags=ardan_norgate+date%3A%3E%3D1994-01-10+) and see the expected JSON, but running the script results in an immediate failure.

**Comment by RedFoxNightfox** [comment]
Due to Cloudflare's DDOS protection, all queries must first pass a captcha.

This blocks all external JSON API calls, which causes the 403 error.

There is nothing wrong with the script, and nothing anyone can do until the DDOS mitigations are over, and the site returns to normal operation.

**Comment by kingretard** [comment]
Ahhhh, okay. I was unaware there were DDOS issues right now. That makes total sense. Thanks!
