### ISSUE TITLE
Error with program.

### ISSUE THREAD

**Issue by darkspyro92** [Wulfre/e621dl#7]
File "e621dl.py", line 145 
        print ''
                 ^ 
SyntaxError: Missing parentheses in call to 'print'

**Comment by Wulfre** [comment]
You need to use python 3. This an error you get when you run the program with python 2. You might have to run the program as `python3 e621dl.py` depending on your operating system.

**Comment by darkspyro92** [comment]
The command python3 isn't recognized. I have Python 3.6. The command I've had to use is py, which has worked.

**Comment by Wulfre** [comment]
Thanks for the information. Can I know your operating system so I can add it to the readme? Ill lookup more information on the commands myself.

**Comment by darkspyro92** [comment]
Windows 10. Also py doesn't work. That's the error I get when I use the py command. I just meant that's the command I've had to use for all the other programs that use python. python3 doesn't work for me.

**Comment by Wulfre** [comment]
My mistake. What just worked for me is `py -3 e621dl.py` let me know if that is a proper solution.

**Comment by darkspyro92** [comment]
Required packages are missing. Run "pip install -r requirements.txt" to install them.

That's what it says when I do the py -3.

**Comment by Wulfre** [comment]
That is a catch that I wrote

**Comment by Wulfre** [comment]
Okay. I have committed a change that should fix the required packages missing and the wrong pip being used to install the packages. [Download the current master branch](https://github.com/Wulfre/e621dl/archive/master.zip) if you want to try it.

**Comment by darkspyro92** [comment]
Alright, thanks. It created the config file. I'm using another program right now, but I'll give it a run when I'm done. Do you know how to make it so it runs every so often to download new stuff? I saw something like that on the page but I'd like to know how to do it with Windows 10.

**Comment by Wulfre** [comment]
With Windows you should be able to use the task scheduler to make the program run automatically.

![Create](http://i.imgur.com/wdBnSQV.png)
![Trigger](http://i.imgur.com/khXNU4S.png)
![Daily](http://i.imgur.com/hwvdOAi.png)
![Action](http://i.imgur.com/vMFhqxf.png)
![Start](http://i.imgur.com/TQPrLvJ.png)

Auto.bat is just the command written in a file so that it can be triggered.
`py -3 e621dl.py --quiet`

**Comment by darkspyro92** [comment]
Alright, thanks! I didn't know about the task scheduler.

**Comment by darkspyro92** [comment]
Hey. I have one last question, if you have the time. If I want to download all the posts from the very first post, what date do I put? I understand it downloads it from the specific time frame, but I'd like to have all posts of specific tags in my folders. I've currently set it to 1080 days, but I know there are posts farther back than that. I don't suppose your code would work setting it to some insane number of days, or is it possible to do years?

**Comment by Wulfre** [comment]
Python usually handles large numbers well and I did account for invalid dates in my code, so there should be no issues. During my testing I just set the number of days to `9999999`.

**Comment by darkspyro92** [comment]
Alright, then. This is going to be something to see. xD Thanks, again. Hope I'm not bothering.

**Comment by darkspyro92** [comment]
Hey so do you mind if I just keep this open? I keep finding other things. I'm trying to download all of them, but it only downloads a certain amount, then closes. I tried upping the max results in constants.py to 9999999, but it doesn't change anything. Any way to fix that? 

With another program I've got thousands of results (and am still not finished from the speed), but I've only got a few hundred with this one. However this one downloads faster and more organized so I like it more.

**Comment by Wulfre** [comment]
You shouldn't need to change anything in the source files. Max results needs to be 320 or else the api breaks. There should be a setting in your config file that you change to 9999999.

**Comment by darkspyro92** [comment]
There isn't. Here's the config file. I'll also change that back.

;;;;;;;;;;;;;;;;;;;
;; MAIN SETTINGS ;;
;;;;;;;;;;;;;;;;;;;

[Settings]
days_to_check = 9999999

[Blacklist]
tags = death, fart, feces, genital_mutilation, genital_torture, genital_trauma, gore, imminent_death, in_utero_penetration, nightmare_fuel, nipple_penetration, peeing, pooping, prolapse, scat, smegma, urethral, urethral_penetration, urine, vomit, watersports, hyper, vore, macro, micro, overweight

;;;;;;;;;;;;;;;;
;; TAG GROUPS ;;
;;;;;;;;;;;;;;;;

; New tag groups can be created by writing the following. (Do not include semicolons.):
; [Directory Name]
; ratings = s, q, e
; min_score = -100
; tags = tag1, tag2, tag3, ...
;
; Example:
; [Cute Cats]
; ratings = s
; min_score = 5
; tags = cat, cute

[Digimon]
ratings = e
min_score = -5
tags = digimon

[Pokemon]
ratings = e
min_score = -5
tags = pokemon

**Comment by Wulfre** [comment]
That looks like it should work, as long as you fix the constants. One of the output lines from the console should say `Checking for new posts since 0001-01-01 (9999999 days).`. If you messed up the files too bad, you can always just download the master files again.

**Comment by darkspyro92** [comment]
The date works, and I changed the number in the constants for Max_Results to 9999999 instead of 320 thinking that would work, but you just said I can't do that. So no telling what to do with that. The program works fine, just won't download all the files in one run.

**Comment by Wulfre** [comment]
I've been testing the program using `days_to_check = 9999999` since I started working on the project, and your config should download every post with the tag you are looking for, minus the posts which are safe, questionable, and under -5 posts, from the beginning of time as long as you are using the master files. There is no code that stops the program from downloading files at any maximum; it keeps going until it cannot find any more posts based on the date that you supply in the config. However, if there is a precisely identifiable problem, I will try my best to find a solution.

**Comment by darkspyro92** [comment]
Alright, thanks. I'll try redownloading it, though, and setting it that way.

**Comment by Wulfre** [comment]
Please, let me know if there is any genuinely confusing information so that I can make it more clear in the readme. I have been doing this entire project without much feedback, so most of the readme is biased by my previous knowledge. I want to make this easily accessible for more people who are interested.

**Comment by darkspyro92** [comment]
Alright. Redownloaded, same problem, however it's not going to download the second group now. Strange.

Also, nobody else is messaging you with information? I'll try to keep you up to date with anything else I find, then.

**Comment by Wulfre** [comment]
I'm not sure how many people are actually using the program, but no. You are the only person to message me with issues so far. Are you getting any errors from the program about urllib or requests? It's strange that it would skip certain posts and groups without giving any errors because it works fine on my end running Windows 10.

**Comment by darkspyro92** [comment]
No errors at all. It just downloads some posts, then the program closes.

**Comment by Wulfre** [comment]
Are you running it through the command prompt, or are you just using the python launcher? It shouldn't matter either way, I'm just trying to collect information.

I used your config file and it looks like it is working as intended.
![Console](http://i.imgur.com/iemV2oc.png)

**Comment by darkspyro92** [comment]
I'm opening it by double-clicked e621dl.py. Does it change if I use the command prompt? I'll give that a go.

**Comment by darkspyro92** [comment]
Jesus with command prompt I got a huge error. I'll post the text, but how did you post your pictures?
http://imgur.com/a/A3hTN

`e621dl      INFO     Running e621dl version 4.0.1 -- Forked from 2.4.6.                                                                                                                                                                                                                                                                                                                                                                                                                   e621dl      INFO     Checking for new posts since 0001-01-01 (9999999 days).                                                                                                                                                                                                                                                                                                                                                                                                              e621dl      INFO     Checking group "Digimon".                                                                                                                                                                                               Traceback (most recent call last):e been downloaded.                                                                                                                                                                                           File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen             291 posts have an unwanted rating.                                                                  chunked=chunked) 3 posts have a low score.                                                                                                                                                                                                 File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request       0 posts are missing a tag.                                                                          six.raise_from(e, None)                                                                                                                                                                                                                    File "<string>", line 2, in raise_from                                                                                                                                                                                                       File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request                                                                                                           httplib_response = conn.getresponse()                                                                                                                                                                                                      File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1331, in getresponse                                                                                                                                     response.begin()                                                                                                                                                                                                                           File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 297, in begin                                                                                                                                            version, status, reason = self._read_status()                                                                                                                                                                                              File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 258, in _read_status                                                                                                                                     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")                                                                                                                                                                                   File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto                                                                                                                                              return self._sock.recv_into(b)                                                                                                                                                                                                             File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1002, in recv_into                                                                                                                                               return self.read(nbytes, buffer)                                                                                                                                                                                                           File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 865, in read                                                                                                                                                     return self._sslobj.read(len, buffer)                                                                                                                                                                                                      File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 625, in read                                                                                                                                                     v = self._sslobj.read(len, buffer)                                                                                                                                                                                                       TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond                                                                                                                                                                                                                                                                     During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                                                                                                                                                                       Traceback (most recent call last):                                                                                                                                                                                                             File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 440, in send                                                                                                                         timeout=timeout                                                                                                                                                                                                                            File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen                                                                                                                 _stacktrace=sys.exc_info()[2])                                                                                                                                                                                                             File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 357, in increment                                                                                                                   raise six.reraise(type(error), error, _stacktrace)                                                                                                                                                                                         File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\packages\six.py", line 685, in reraise                                                                                                                   raise value.with_traceback(tb)                                                                                                                                                                                                             File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen                                                                                                                 chunked=chunked)                                                                                                                                                                                                                           File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request                                                                                                           six.raise_from(e, None)                                                                                                                                                                                                                    File "<string>", line 2, in raise_from                                                                                                                                                                                                       File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request                                                                                                           httplib_response = conn.getresponse()                                                                                                                                                                                                      File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1331, in getresponse                                                                                                                                     response.begin()                                                                                                                                                                                                                           File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 297, in begin                                                                                                                                            version, status, reason = self._read_status()                                                                                                                                                                                              File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 258, in _read_status                                                                                                                                     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")                                                                                                                                                                                   File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\socket.py", line 586, in readinto                                                                                                                                              return self._sock.recv_into(b)                                                                                                                                                                                                             File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1002, in recv_into                                                                                                                                               return self.read(nbytes, buffer)                                                                                                                                                                                                           File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 865, in read                                                                                                                                                     return self._sslobj.read(len, buffer)                                                                                                                                                                                                      File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 625, in read                                                                                                                                                     v = self._sslobj.read(len, buffer)                                                                                                                                                                                                       urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))                                                                                                                                                                                                                                                                                                                                                                                                                                            During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                                                                                                                                                                       Traceback (most recent call last):                                                                                                                                                                                                             File "e621dl.py", line 111, in <module>                                                                                                                                                                                                        results = remote.get_posts(search, check_date, i + 1, constants.MAX_RESULTS, session)                                                                                                                                                      File "C:\Users\umbre\Desktop\PrivateFiles\e621Downloader\e621dlWulfre\e621dl-master\lib\remote.py", line 15, in get_posts                                                                                                                      return session.get(request).json()                                                                                                                                                                                                         File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 515, in get                                                                                                                          return self.request('GET', url, **kwargs)                                                                                                                                                                                                  File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 502, in request                                                                                                                      resp = self.send(prep, **send_kwargs)                                                                                                                                                                                                      File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 612, in send                                                                                                                         r = adapter.send(request, **kwargs)                                                                                                                                                                                                        File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 490, in send                                                                                                                         raise ConnectionError(err, request=request)                                                                                                                                                                                              requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))`

**Comment by Wulfre** [comment]
Okay, so it has something to do with your connection with e621's server. I can see that you are getting some response because the filter went through a few hundred posts. Let me tweak the download methods and see if that helps. I'll message again when once I push to the master.

**Comment by Wulfre** [comment]
Okay, by default requests times out immediately, so I increased the timeout to 5 seconds and also made it retry the connection if it drops.

**Comment by darkspyro92** [comment]
Alright. I hope that does something. Redownload it now?

**Comment by Wulfre** [comment]
Yes, just make sure you take the master branch and not the release.

**Comment by darkspyro92** [comment]
It's running, but getting an occasional error.

urllib3.connectionpool WARNING  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='e621.net', port=443): Read timed out. (read timeout=5)",)': /post/index.json?tags=digimon%20date:%3E0001-01-01&page=2&limit=320

**Comment by darkspyro92** [comment]
Also trying to copy that with ctrl + c (forgetting that shift + right click is to copy on command prompt) apparently cancels the program. Is that a python thing or command prompt thing?

**Comment by Wulfre** [comment]
`ctrl + c` canceling the program is a command prompt thing.
That message is just warning that the connection timed out. I haven't had a problem with my own connection dropping so I haven't seen it before. I'll look into catching the message and making it more clean for end-users. Let me know if you get all, or at least a large number, of the posts downloaded. In the worst case scenario, I could just include an setting in the config to disallow timing out for users with a slow connection, however that could also lead to the program hanging forever if e621's server happens to be down, which could also be worrying to users.

**Comment by darkspyro92** [comment]
Well it's over 320, so that's a milestone.

**Comment by darkspyro92** [comment]
Also I would agree not disallowing timing out. Maybe give the ability for users to set their own timeout just in case of slow connections? Then they can increase it if they keep getting timed out until they find something that works.

**Comment by Wulfre** [comment]
Okay, the new master will let you set your own timeout by using the `connection_timeout = x` value in the settings section of `config.ini`. If you set the number to anything negative, the program will run indefinitely.

**Comment by darkspyro92** [comment]
Count has exceed 2400 posts. It's working perfectly now. The timeout must have been the problem, then. That's awesome.

**Comment by Wulfre** [comment]
I'm glad it was worth the 4 hours. Could I ask what your timeout is so that I can come up with a good default?

**Comment by darkspyro92** [comment]
I didn't download the new branch yet, haha. I'm still at the default 5 you set it at. Also, sorry for costing you that much time.

**Comment by Wulfre** [comment]
I didn't mean that in a negative way, I don't do much on Saturday nights so at least I could do something productive. I removed the retries in the newest push because I felt like it was making the connection too complicated. I needed to hack together two modules to make it work. If that breaks anything for you, you might try increasing the timeout, or I can put it back.

**Comment by darkspyro92** [comment]
Well once this finishes, I'll take the new release and give it a run through and then tell you what happened. Do I have to redownload the whole branch, or are there certain files I can replace? I might be able to just copy the downloads since they would have the same file names anyways.

**Comment by Wulfre** [comment]
All you need to replace is e621dl.py and the 3 modules in the lib folder.

**Comment by darkspyro92** [comment]
I still haven't downloaded the new one, but the one I'm using is working fine. However it may take a few days. There's a lot of posts for Pokémon. 

25567 posts have been downloaded.                                                                                       
27 posts are already in storage. tag.                                                                                   
16559 posts have an unwanted rating.                                                                                    
96 posts have a low score.                                                                                              
2565 posts contain a blacklisted tag.                                                                                   
0 posts are missing a tag.   

And it's not even a quarter of the way there. xD

**Comment by darkspyro92** [comment]
Alright, I downloaded the new one, and it worked when I set it to 9999999 days. Now I set it to 2 days and have it run every day to keep an up-to-date folder, and I got another error.
http://imgur.com/a/WQazY

**Comment by Wulfre** [comment]
Okay, that should be an easy error to catch and give the user better information. The request timed out, just increase your timeout setting in config.ini

```
[Settings]
connection_timeout = 15
```

**Comment by darkspyro92** [comment]
Huh. I left it at 5 like you had it originally. Strange that setting it myself changed it.

**Comment by darkspyro92** [comment]
No wait, it didn't work with 9999999 days. That was the old one. It didn't work at all with the connection timeout. I'll set it, though.

**Comment by darkspyro92** [comment]
Alright, it's working now! I'd post the results, but Windows Powershell isn't copy-paste friendly, and don't think it's worth taking the time to take a picture. Thanks, though! :D I'll let you know if anything else happens.

**Comment by Wulfre** [comment]
Just to confirm, setting the timeout to 15 seconds fixed it? I might increase the default timeout.

**Comment by darkspyro92** [comment]
Yeah it did, but I'm still surprised. When you forced it to 5 on the previous build it worked fine. I'm not sure why giving me the choice made a change. I have very good internet connection and bandwidth as well.

**Comment by Wulfre** [comment]
The previous commit did 5 retries of 5 seconds, so it was similar to having 25 seconds of timeout. 

I've only tested the program on my own internet, which is actually below average, so I am also surprised that anyone is having connectivity issues on their own side, it would be a different story if it was e621's side. I currently don't have much knowledge on how to the connection is handled by the request module I'm using, because I never had any issues on my own. I might need to read up for future updates.

**Comment by darkspyro92** [comment]
Alright, well 15 works for me and mine's above average so that means that's good for higher end internet I'm guessing. 25+ for lower end and just in case e621 goes down.

**Comment by Wulfre** [comment]
What I'm confused about is why I didn't encounter any problems with the module's default timeout, which I believe is just to wait until the connection closes itself.  I'll do more research into the remote side of this program. A lot of my recent focus has been on the local side -- filtering efficiency and such.

**Comment by darkspyro92** [comment]
Alright, then.

**Comment by Wulfre** [comment]
I'm going to have to test the program on another network, because even after removing the timeout completely and ruining my incoming packets --

![clumsy](https://i.imgur.com/8VDNotA.png)

-- all my connections are successful.

**Comment by darkspyro92** [comment]
Huh. Well I don't think it uses that much network, so it probably won't do much.

**Comment by Wulfre** [comment]
I'm just trying to figure out why you got so many errors a few days ago.

**Comment by darkspyro92** [comment]
Have you made any progress on it? I'm not sure what it could be either. Maybe because of the retries it had it run through each 5 seconds and succeeded once?

**Comment by Wulfre** [comment]
I restored it to the default configuration, cleaned up the code some more, and added new features. Not sure if you will have a problem again, but I tested it on my normal and throttled network and it worked as expected.

**Comment by darkspyro92** [comment]
Well now I'm having a weird problem. Now I'm trying to do Undertale with a rating = e, but I'm only getting s rating pictures. It's working with my other groups but not this one. I'm up to five groups now, so I'm wondering if more than three breaks it?

**Comment by darkspyro92** [comment]
Btw, I don't have the newest branch. I'll download it and try again, although I don't think that will change much.

**Comment by darkspyro92** [comment]
Alright. Just downloaded the new update, and it thinks that Settings and Blacklist are groups now. That's probably not right haha.

**Comment by Wulfre** [comment]
Ive been updating the program and not leaving too many obvious notes. There is no more settings. Check constants.py to see the newest config format. Also, it should be ratings = e. Ill put in some typo detection because I even find myself typing rating.

**Comment by darkspyro92** [comment]
Oh! Alright. I typed rating as well, haha. I'll give it another run now with the updated config.

**Comment by darkspyro92** [comment]
Okay so apparently my first three groups worked, then it got to Undertale and went to crap.

http://imgur.com/a/lpEOb

**Comment by darkspyro92** [comment]
It was a failed connection to the server again I think. The second half looks like lost connection, but not sure about the first part. I guess you removed the timeout delay?

**Comment by Wulfre** [comment]
I removed the timeout completely, so the connection is being closed by e621, for whatever reason, I don't think that their server timeouts are public.

**Comment by darkspyro92** [comment]
It seemed to work before. Would it be possible to try again?

**Comment by darkspyro92** [comment]
What's the code for the timeout? I'll put it in and test it for you to see what happens. You don't need to put it in the public build.

**Comment by Wulfre** [comment]
Anywhere in the remote.py file where I use `session.get(request)` you need to add `session.get(request, timeout=seconds)`.

Sorry for not getting back to your last comment, I have been busy with school starting.

**Comment by darkspyro92** [comment]
It's fine. I understand. I hope school goes well for you. You're a computer programming major, I take it?

**Comment by darkspyro92** [comment]
Hey. Been a while. Hope you're doing well.

Just messaging because I seem to have a problem my e621dl program. It was working fine before but I'm not sure what happened. By the looks of the error it's on e621's side?

`e621dl      INFO     Running e621dl version 4.4.1.                                                                                                                                                                                              e621dl      INFO     Checking for partial downloads.                                                                    remote      INFO     Partial download found: 1414428.png.request. Finishing download.                                   Traceback (most recent call last):                                                                                        File "e621dl.py", line 34, in <module>                                                                                    remote.finish_partial_downloads(session)                                                                              File "F:\PrivateFiles\e621Downloader\e621dlWulfre\lib\remote.py", line 134, in finish_partial_downloads                   download_post(url, path, session)                                                                                     File "F:\PrivateFiles\e621Downloader\e621dlWulfre\lib\remote.py", line 116, in download_post                              response = session.get(url, stream = True, headers = header)                                                          File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 515, in get     return self.request('GET', url, **kwargs)                                                                             File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 488, in request                                                                                                                         prep = self.prepare_request(req)                                                                                      File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 431, in prepare_request                                                                                                                 hooks=merge_hooks(request.hooks, self.hooks),                                                                         File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 305, in prepare                                                                                                                           self.prepare_url(url, params)                                                                                         File "C:\Users\umbre\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 379, in prepare_url                                                                                                                       raise MissingSchema(error)                                                                                          requests.exceptions.MissingSchema: Invalid URL '/images/deleted-preview.png': No schema supplied. Perhaps you meant http:///images/deleted-preview.png?   `

**Comment by Wulfre** [comment]
Oh, that's a really weird case that I didn't think of. The post started to download, but during the time between the partial download and you restarting the program, it was deleted so there is no url for the program to finish the download. Just delete the file and it should start working normally.

**Comment by darkspyro92** [comment]
Alright, thanks.

**Comment by darkspyro92** [comment]
I've got another weird case now. For some reason it brings up a rating conflict for all posts for one of my searches.

`┌──────────────────────────────────────────────────────────────────────┐                   │                              Undertale                               │                   ├────────────┬───────────┬─────────────────┬─────────────┬─────────────┤                   │ downloaded │ duplicate │ rating conflict │ blacklisted │ missing tag │                   ├────────────┼───────────┼─────────────────┼─────────────┼─────────────┤                   │     0      │     0     │      8800       │     535     │    4118     │                   └────────────┴───────────┴─────────────────┴─────────────┴─────────────┘ 

`[Undertale]
;days_to_check = 1
ratings = e
min_score = -5
tags = Undertale, -mettaton, -mettaton_ex, -sans_(undertale), -papyrus_(undertale)

I put the semicolon before days_to_check so it would automatically go for the default of 9999999 so I can download all posts. All this has been working for all of my searches except for this one. I know the tags are right because this search has worked before. Now it just gives rating conflicts and missing tags... Not sure what changed unless it was the program. Any ideas?

Also dat cute Ice Bear. xP

**Comment by Wulfre** [comment]
Okay, this has to do with the program only allowing 4 actual search tags. Any tags over the 4th are filtered after the search. So that search is basically going through every post on the site looking for ones tagged with undertale. I could probably fix this by making a sub-blacklist for each search so that the not tags don't take up those 4 slots.

**Comment by darkspyro92** [comment]
Oh. Well I can just add those tags in my blacklist since I don't want to see those irregardless. A sub-blacklist could be convenient, but it'd probably be a pain to implement.

**Comment by darkspyro92** [comment]
I seem to have another error. I just got a new computer so it might not be recognizing that I redownloaded Python?

(It goes too fast for me to copy this time since I can't use the py command for some reason, so I took a screenshot.)

[
![pyerror](https://user-images.githubusercontent.com/22324730/37051172-b66c9058-2143-11e8-8a39-982ec43b43b6.png)
](url)

**Comment by Wulfre** [comment]
The exe version should work without pyton even installed. I'll have to do some testing. From just a brief look, it seems like an issue with your config, so if you wouldn't mind posting that I'll look at it also.

**Comment by darkspyro92** [comment]
*facepalm* I found what was wrong. I was trying to download things from an artist that's only on e621, but it had a degree symbol in it so it didn't parse it.

[Artists]
;days_to_check = 14
ratings = e
min_score = -1
tags = 29ºc, g-sun

**Comment by Wulfre** [comment]
It's actually not even the degree symbol, which might be why it's not parsing, but I do have strings encoded in unicode, so I expected it to work. I'll have to do some research.

**Comment by darkspyro92** [comment]
Well it worked when I removed that part, so that's all I can figure.

**Comment by Wulfre** [comment]
Okay, I figured it out. I did write the program to decode utf-8, but you need to make sure your config is also encoded in utf-8. I am assuming you are using notepad, so when saving the file make sure to change the encoding to utf-8 at the bottom of the save as window next to the save button.

**Comment by darkspyro92** [comment]
Ah. Huh. I had it in ANSI which is the default.
